"use client";

import { useEffect, useRef, useState } from "react";
import { Reveal } from "@/components/motion/fade-in";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useBrain } from "@/components/story/brain-provider";
import { StoryView } from "@/components/story/story-view";
import { StoryChat } from "@/components/story/story-chat";
import { StoryTranslating } from "@/components/story/story-translating";
import { BiographerSkeleton } from "@/components/story/story-loading-skeletons";
import { useLocale } from "@/components/locale/locale-provider";
import type { DevStory } from "@/lib/devstory/story";
import type { StoryDataSnapshot } from "@/lib/devstory/minify";
import type { Locale } from "@/lib/i18n/dictionary";
import { BookOpen, Sparkles, AlertTriangle } from "lucide-react";

const STORAGE_KEY = "devstory-story";

type PersistedStory = {
  username: string;
  storyId: string | null;
  story: DevStory;
  mode: "ai" | "mock";
  authoredLocale: Locale;
  translations: Partial<Record<Locale, DevStory>>;
  data: StoryDataSnapshot | null;
};

export function StoryGenerator({
  username,
  onLoadingChange,
}: {
  username: string;
  onLoadingChange?: (loading: boolean) => void;
}) {
  const { t, locale } = useLocale();
  const { brain, brainLoading, setBrain } = useBrain();
  const [story, setStory] = useState<DevStory | null>(null);
  const [storyId, setStoryId] = useState<string | null>(null);
  const [displayName, setDisplayName] = useState(username);
  const [authoredLocale, setAuthoredLocale] = useState<Locale>("en");
  const [translations, setTranslations] = useState<
    Partial<Record<Locale, DevStory>>
  >({});
  const [mode, setMode] = useState<"ai" | "mock" | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [failedLocales, setFailedLocales] = useState<Locale[]>([]);
  const [hydrated, setHydrated] = useState(false);
  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    let active = true;
    queueMicrotask(() => {
      if (!active) return;
      autoGeneratedRef.current = false;
      setHydrated(false);
      setStory(null);
      setStoryId(null);
      setMode(null);
      setTranslations({});
      setError(null);
      setFailedLocales([]);
      setDisplayName(username);
      setLoading(false);

      try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (!raw) {
          setHydrated(true);
          return;
        }
        const parsed = JSON.parse(raw) as PersistedStory;
        if (!parsed?.story || parsed.username !== username) {
          setHydrated(true);
          return;
        }
        if (parsed.mode === "mock") {
          window.localStorage.removeItem(STORAGE_KEY);
          setHydrated(true);
          return;
        }
        setStory(parsed.story);
        setStoryId(parsed.storyId ?? null);
        setMode(parsed.mode ?? "mock");
        setAuthoredLocale(parsed.authoredLocale ?? "en");
        setTranslations(parsed.translations ?? {});
        setDisplayName(parsed.data?.name ?? username);
        if (parsed.data) {
          setBrain(parsed.data);
        }
      } catch {}
      setHydrated(true);
    });
    return () => {
      active = false;
    };
  }, [username, setBrain]);

  useEffect(() => {
    onLoadingChange?.(loading || brainLoading);
  }, [loading, brainLoading, onLoadingChange]);

  useEffect(() => {
    if (!story || mode === "mock" || !brain) return;
    try {
      window.localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({
          username,
          storyId,
          story,
          mode: mode ?? "ai",
          authoredLocale,
          translations,
          data: brain,
        } satisfies PersistedStory),
      );
    } catch {}
  }, [story, storyId, mode, authoredLocale, translations, brain, username]);

  useEffect(() => {
    if (!hydrated || story || loading || brainLoading || !brain) return;
    if (autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hydrated, story, loading, brainLoading, brain, username]);

  async function handleGenerate() {
    if (!brain) {
      setError(t.generator.failed);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/story/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, locale, brain }),
        cache: "no-store",
      });
      const json = (await res.json()) as {
        id?: string | null;
        story?: DevStory;
        mode?: "ai" | "mock";
        data?: StoryDataSnapshot | null;
        error?: string;
      };
      if (!res.ok) {
        throw new Error(json.error ?? t.generator.failed);
      }
      if (!json.story) throw new Error(t.generator.failed);
      setStory(json.story);
      setStoryId(json.id ?? null);
      setMode(json.mode ?? "mock");
      setAuthoredLocale(json.mode === "ai" ? locale : "en");
      setTranslations({});
      setFailedLocales([]);
      setDisplayName(brain.name ?? username);
    } catch (e) {
      setError(e instanceof Error ? e.message : t.generator.failed);
    } finally {
      setLoading(false);
    }
  }

  const translationFailed = failedLocales.includes(locale);
  const translating = Boolean(
    story &&
      locale !== authoredLocale &&
      !translations[locale] &&
      !translationFailed,
  );
  const activeStory = translations[locale] ?? story;

  useEffect(() => {
    if (!story || locale === authoredLocale || translations[locale]) return;
    let active = true;
    (async () => {
      try {
        const res = await fetch("/api/story/translate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            story,
            sourceLocale: authoredLocale,
            targetLocale: locale,
          }),
        });
        if (!res.ok) {
          if (active) {
            setFailedLocales((prev) =>
              prev.includes(locale) ? prev : [...prev, locale],
            );
          }
          return;
        }
        const json = (await res.json()) as { story: DevStory };
        if (active) {
          setTranslations((prev) => ({ ...prev, [locale]: json.story }));
        }
      } catch {
        if (active) {
          setFailedLocales((prev) =>
            prev.includes(locale) ? prev : [...prev, locale],
          );
        }
      }
    })();
    return () => {
      active = false;
    };
  }, [story, locale, authoredLocale, translations]);

  const showLoading = loading;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <p className="font-mono text-xs font-bold tracking-[0.2em] text-muted-foreground uppercase">
            {t.generator.phase}
          </p>
          <h2 className="mt-1 font-heading text-2xl font-black tracking-normal text-balance uppercase">
            {t.generator.titleFor(username)}
          </h2>
        </div>
        <Button
          onClick={() => void handleGenerate()}
          disabled={loading || translating || !brain}
          size="sm"
        >
          <Sparkles className="text-bauhaus-yellow" />
          {loading
            ? t.generator.writing
            : story
              ? t.generator.rewrite
              : t.generator.generate}
        </Button>
      </div>

      {showLoading && (
        <Reveal variant="enter" key="generating">
          <BiographerSkeleton statusLabel={t.generator.readingFor(username)} />
        </Reveal>
      )}

      {error && (
        <Card className="border-destructive bg-destructive/10 shadow-none">
          <CardContent className="flex items-center gap-2 py-4 font-mono text-sm font-bold text-destructive uppercase">
            <AlertTriangle className="size-4" />
            {error}
          </CardContent>
        </Card>
      )}

      {!story && !loading && !hydrated && (
        <Reveal variant="enter" key="hydrating">
          <BiographerSkeleton statusLabel={t.generator.readingFor(username)} />
        </Reveal>
      )}

      {!story && !loading && hydrated && error && (
        <Reveal variant="subtle" key="retry">
        <Card className="border-2 border-dashed border-foreground/40 bg-muted/30 shadow-none">
          <CardContent className="flex flex-col items-center gap-4 py-10 text-center sm:py-12">
            <span className="flex size-12 items-center justify-center rounded-none border-2 border-foreground bg-bauhaus-deep shadow-hard-sm">
              <BookOpen className="size-5 text-bauhaus-yellow" />
            </span>
            <div className="max-w-md space-y-2">
              <h3 className="font-heading text-lg font-black tracking-normal uppercase">
                {t.generator.emptyTitle}
              </h3>
              <p className="text-sm text-muted-foreground text-pretty">
                {t.generator.emptyBody(username)}
              </p>
            </div>
            <Button onClick={() => void handleGenerate()} size="lg" disabled={!brain}>
              <Sparkles className="text-bauhaus-yellow" />
              {t.generator.emptyCta}
            </Button>
          </CardContent>
        </Card>
        </Reveal>
      )}

      {story && !loading && (
        <>
          {translating ? (
            <StoryTranslating />
          ) : (
            <>
              {translationFailed && locale !== authoredLocale && (
                <p className="mb-4 font-mono text-xs font-bold tracking-wider text-muted-foreground uppercase">
                  {t.generator.translationFailed}
                </p>
              )}
              <StoryView
                story={activeStory ?? story}
                mode={mode ?? "mock"}
                username={username}
                displayName={displayName}
                brain={brain}
                storyId={storyId}
              />
            </>
          )}
        </>
      )}

      {story && !loading && (
        <StoryChat
          story={activeStory ?? story}
          brain={brain}
          username={username}
        />
      )}
    </div>
  );
}
