export const TOKEN_IDS = [
  "sprout",
  "spark",
  "frame",
  "bridge",
  "flame",
  "peak",
  "compass",
  "rocket",
  "tide",
  "labyrinth",
  "key",
  "roots",
  "dawn",
  "orbit",
  "signal",
  "current",
  "forge",
  "gate",
  "mirror",
  "constellation",
  "scroll",
  "lens",
  "shield",
  "thread",
  "prism",
  "quill",
  "anchor",
  "pulse",
  "beacon",
  "hourglass",
  "canyon",
  "harbor",
  "knot",
  "wing",
  "crater",
  "mosaic",
  "sundial",
  "ledger",
  "vault",
  "circuit",
  "lantern",
  "helm",
  "cascade",
  "keystone",
  "chisel",
  "spire",
  "vector",
  "ember",
  "loom",
  "echo",
  "sonar",
] as const;

export type TokenId = (typeof TOKEN_IDS)[number];

export const TOKEN_MEANINGS: Record<TokenId, string> = {
  sprout: "beginnings, first steps, a seed planted",
  spark: "an idea ignites, curiosity sparks",
  frame: "structure, foundations, frameworks",
  bridge: "connecting things, integrating, refactoring",
  flame: "rewrites, burning it down and rebuilding",
  peak: "mastery, summits reached, hard-won skill",
  compass: "exploration, finding direction",
  rocket: "shipping, launching, going public",
  tide: "flow, steady streams of work, momentum",
  labyrinth: "long debugging journeys, deep complexity",
  key: "breakthroughs, unlocking something",
  roots: "deepening, growing in place",
  dawn: "new beginnings, first light after a long night",
  orbit: "consistent rhythm, rounds of iteration, satellite work",
  signal: "communication, APIs, messages sent and received",
  current: "momentum, continuous delivery, being in the flow",
  forge: "craftsmanship, building tools, hammering out details",
  gate: "checkpoints passed, releases, milestones cleared",
  mirror: "reflection, learning from mistakes, honest self-review",
  constellation: "many small pieces forming a bigger picture",
  scroll: "documentation, reading the docs, writing it down",
  lens: "inspection, debugging, seeing what others missed",
  shield: "hardening, reliability, guarding the system",
  thread: "async work, concurrency, many strands at once",
  prism: "polyglot work, many languages refracting one problem",
  quill: "authorship, craft in the editor, leaving a signature",
  anchor: "stability, maintenance, holding the ship steady",
  pulse: "rhythm, iteration, the heartbeat of shipping",
  beacon: "visibility, calling others in, open source lighthouse",
  hourglass: "slow builds, patience, long projects measured in seasons",
  canyon: "going deep, narrow specialization, vertical expertise",
  harbor: "a home base repo, safe return, long-term maintenance",
  knot: "tangled complexity finally understood, legacy untied",
  wing: "ambition lifting off, leveling up, reaching higher",
  crater: "crash and rebuild, post-mortem honesty, starting over",
  mosaic: "many small repos forming a larger portrait",
  sundial: "measured pace, time as ally, the long game",
  ledger: "data, state, backends, accounting for what happened",
  vault: "security, privacy, locking down what matters",
  circuit: "low-level craft, embedded thinking, wires and logic",
  lantern: "illumination, teaching, docs that light the path",
  helm: "steering architecture, taking the wheel, leadership",
  cascade: "pipelines, waterfalls of features, flow through stages",
  keystone: "the piece that holds everything together, capstone work",
  chisel: "refinement, carving detail, polishing until it fits",
  spire: "vertical ambition, reaching higher, building upward",
  vector: "direction chosen, velocity in one heading, purposeful motion",
  ember: "slow persistent burn, quiet heat that never quite goes out",
  loom: "weaving systems together, threads crossing into fabric",
  echo: "feedback loops, iteration answering iteration, resonance",
  sonar: "probing depth, sending pings into the unknown",
};

/** Compact gallery for AI prompts (system + uniqueness blocks). */
export const TOKEN_GALLERY_TEXT = TOKEN_IDS.map(
  (t) => `${t} (${TOKEN_MEANINGS[t]})`,
).join("; ");

export function pickTokenForName(name: string): TokenId {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
  }
  return TOKEN_IDS[hash % TOKEN_IDS.length];
}
